# Generated by Django 3.2 on 2023-01-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('LastBidder', models.CharField(max_length=50)),
                ('LastBid', models.IntegerField()),
                ('BuyNowPrice', models.IntegerField()),
                ('Image', models.CharField(max_length=100)),
            ],
        ),
    ]
