# Generated by Django 3.2 on 2023-01-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('BoughtId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('BoughtPrice', models.IntegerField()),
                ('Owner', models.CharField(max_length=50)),
                ('Image', models.CharField(max_length=100)),
            ],
        ),
    ]
